name: publish-codercom

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  IMAGE_NAME: code-server
  IMAGE_VERSION: 4.2.0
  GHCR_REGISTRY: ghcr.io
  GHCR_USER: ${{ github.repository_owner }}
  GHCR_IMAGE: ${GHCR_REGISTRY}/${GHCR_USER}/${IMAGE_NAME}
  QUAY_REGISTRY: quay.io
  QUAY_USER: ${{ github.repository_owner }}
  QUAY_IMAGE: ${QUAY_REGISTRY}/${QUAY_USER}/${IMAGE_NAME}


jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/docker/login-action
      - name: Log into GitHub Container Registry
        if: github.event_name == 'pull_request'
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/login-action
      - name: Log into Quay Container Registry
        if: github.event_name == 'pull_request'
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.QUAY_REGISTRY }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: kludge - build codercom
        run: |
          . hacks/local_docker_build.sh
          code_server_build codercom

      - name: kludge - push codercom
        if: github.event_name == 'pull_request'
        run: |
          TYPE=codercom
          docker tag custom-code-server:${TYPE}-base ${{ env.QUAY_IMAGE }}:${TYPE}-base
          docker tag custom-code-server:${TYPE} ${{ env.QUAY_IMAGE }}:${TYPE}

          docker push ${{ env.QUAY_IMAGE }}:${TYPE}-base
          docker push ${{ env.QUAY_IMAGE }}:${TYPE}
